### ISSUE TITLE
关于机器人验证的一些不太好的体验

### ISSUE THREAD

**Issue by wohaishixinren** [axumrs/roaming-axum#3]
首先很感谢提供的学习网站，条理清晰，重点明确。然后看到是简体中文，感觉也是为了大陆提供的内容。但是这个机器人验证有时候真的很让人捉急，每次有种用2g网刷网页的感觉：
1. 谷歌自动验证，这个正常来说肯定是不能用的。那么我只能每次都要等待连接不上谷歌了，对于正常上网的人来说属实浪费了资源。
2. 跳转到手动验证。但是中间这个过程真的很长。有时候设置几分钟。
最后，能不能改进下，两个验证同时提供，对于网络不好的，直接使用手动验证。或者减少下等待谷歌的时间。

**Comment by axumrs** [comment]
有关人机验证的事项，请关注TG群。我们在TG群里多次进行了说明。
